### ISSUE TITLE
How can I download FacesDB?

### ISSUE THREAD

**Issue by TonyDandelion** [gauravtheP/Real-Time-Facial-Expression-Recognition#1]
Hello, your work is so brilliant! And I want to run your code, But I can not download the FacesDB. I have tried to download from the web page  (http://app.visgraf.impa.br/database/faces/download-with-email/). However it didn't work.

First all, I input my email address, chose all persons, all poses and bmp extension.  After that,  I clicked the download button.

But I haven't receive any download link in my email Inbox.

So, please tell me how can i download the dataset FacesDB.

**Comment by gauravtheP** [comment]
I am closing this issue here.
Any further communication shall be done via email.
