### ISSUE TITLE
Same piece of code, run many times, appear different error

### ISSUE THREAD

**Issue by lenghanyan** [gauravtheP/Real-Time-Facial-Expression-Recognition#2]
Hello, I ran your code and the following error occurred. Could you help me ?
![error1](https://user-images.githubusercontent.com/33375947/49791551-b1232a80-fd6b-11e8-9c52-e12a20e3d88d.png)
![error2](https://user-images.githubusercontent.com/33375947/49791553-b1bbc100-fd6b-11e8-81fc-7db29a515514.png)
![error3](https://user-images.githubusercontent.com/33375947/49791554-b1bbc100-fd6b-11e8-9d0c-f7e2df81233f.png)

**Comment by gauravtheP** [comment]
Communication shall be done via Email

**Comment by kosehy** [comment]
Hello, I also met same error above.

![image](https://user-images.githubusercontent.com/10434273/54336166-ab8cf780-466e-11e9-98ae-0e89558a661f.png)

Could you also help me to solve above error?

Thanks!

**Comment by gauravtheP** [comment]
Hello,
I am so sorry for replying you late. I was quite busy with my work.

Here, check that you have to pass an array of dimension (10*350*350*3). It
means that there are 10 images and each images is of size 350*350*3. So,
just check the size of your array and pass array of 4 dimensions like this.
