### ISSUE TITLE
The result is too poor.

### ISSUE THREAD

**Issue by xiaoxianggong** [gauravtheP/Real-Time-Facial-Expression-Recognition#4]
Hello, I run the code according to what you said, the result recognition effect is as shown in the figure: What is the reason?
![image](https://user-images.githubusercontent.com/49088671/55272687-33bffd80-52fb-11e9-98eb-d8af5d780ae4.png)

**Comment by xiaoxianggong** [comment]
![image](https://user-images.githubusercontent.com/49088671/55272906-2b69c180-52ff-11e9-86e6-566f73f0cf5c.png)

**Comment by gauravtheP** [comment]
Hi, 
You can improve result by following two ways:
1. Add more images in training data. I know the number of images in training data are less. Remember that the new images should be very clear with 95% of the image should be covered with face from head to chin.
2. Increase the size of image from 350*350 to 500*500 for better detection.
